FROM python:3.11.5 AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --user -r requirements.txt

COPY . .

FROM scratch

COPY --from=builder /root/.local /root/.local
COPY --from=builder /app /app

WORKDIR /app

ENV PATH=/root/.local/bin:$PATH

CMD ["python", "app.py"]